config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get "/topics/new", to: "topics#new", as: :new_topic
  post "/topics", to: "topics#create", as: :topics
  get "/topics/:id", to: "topics#show", as: :topic

  post "/posts", to: "posts#create"
  get "/posts/:id", to: "posts#show", as: :post

  namespace :api do
    namespace :v1 do
      get "/topics", to: "topics#index"
      get "/topics/:id", to: "topics#show"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true
  belongs_to :topic,required: true
  belongs_to :user, required: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < ApplicationController
  def index
    begin
      @pagy, @topics = pagy(Topic.all)
      #render json: @topics.all, status: :ok
      render json: TopicSerializer.new(@topics).serializable_hash.to_json, status: :ok
    rescue Pagy::OverflowError
      render json: { error: 'No such page', status: :not_found }
    end
  end

  def show
    begin
      @topic = Topic.find(params[:id])
      @pagy, @posts = pagy(@topic.posts)
      render json: PostSerializer.new(@posts).serializable_hash.to_json, status: :ok
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'No such topic', status: :not_found }
    rescue Pagy::OverflowError
      render json: { error: 'No such page', status: :not_found }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_post, only: [:show, :edit]

  def edit
  end

  def show
  end

  def create
    @post = Post.create(post_post_params)
    @post.user = current_user

    if @post.save
      redirect_to topic_path(@post.topic), notice: "Post Successfully created"
    else
      redirect_to topic_path(@post.topic), notice: "Post failed to created"
    end
  end

  private
  def post_post_params
    params.require(:post).permit(:body, :topic_id)
  end

  def set_post
    begin
      @post = Post.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: :show
  before_action :authenticate_user!, only: %i[new create]

  def show
    @pagy, @posts = pagy(@topic.posts)
  end

  def new
    @topic = Topic.new
    @topic.posts.new
  end

  def create
    @topic = Topic.new(topics_post_params)
    @topic.posts.each do |post|
      post.user = current_user
    end
    if @topic.save
      redirect_to topic_path(@topic), notice: 'Topic was successfully updated.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def topics_post_params
    params.require(:topic).permit(:title, posts_attributes: [:body])
  end

  def set_topic
    @topic = Topic.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EksiRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <nav
        class="fixed inset-x-0 top-0 z-10 w-full px-4 py-1 bg-white shadow-md border-slate-500 dark:bg-[#0c1015] transition duration-700 ease-out"
      >
        <div class="flex justify-between p-4">
          <div class="text-[2rem] leading-[3rem] tracking-tight font-bold text-black dark:text-white">
            <%= link_to "EksiRails", root_path %>
          </div>
          <div class="flex items-center space-x-4 text-lg font-semibold tracking-tight">
          <% if user_signed_in? %>
              <%= link_to "New Topic", new_topic_path, class: "px-6 py-2 text-black transition duration-700 ease-out bg-white border border-black rounded-lg hover:bg-black hover:border hover:text-white dark:border-white dark:bg-inherit dark:text-white dark:hover:bg-white dark:hover:text-black"%>
              <%= button_to "Log Out", destroy_user_session_path, :method => :delete,class: "px-6 py-2 text-black transition duration-700 ease-out bg-white border border-black rounded-lg hover:bg-black hover:border hover:text-white dark:border-white dark:bg-inherit dark:text-white dark:hover:bg-white dark:hover:text-black"%>
          <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "px-6 py-2 text-black transition duration-700 ease-out bg-white border border-black rounded-lg hover:bg-black hover:border hover:text-white dark:border-white dark:bg-inherit dark:text-white dark:hover:bg-white dark:hover:text-black"%>
              <%= link_to "Sign up", new_user_registration_path, class: "px-6 py-2 text-white transition duration-500 ease-out bg-blue-700 rounded-lg hover:bg-blue-800 hover:ease-in hover:underline" %>
          <% end %>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="flex flex-row">
          <div class="basis-2/12">
            <p class="font-bold text-3xl mb-3">Topics</p>
            <% Topic.all.each do |topic| %>
              <p class="pb-1.5 hover:bg-gray-100"><%= link_to topic.title + " (#{topic.posts.count}) ", topic%></p>
            <% end %>
          </div>
          <div class="basis-8/12 content-start"><%= yield %></div>
          <div class="basis-2/12 font-bold text-3xl mb-3">Extra</div>
        </div>
      </div>

    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="max-w w-full bg-white p-8 rounded-lg">
    <%= form.hidden_field :topic_id%>
    <%= form.label :body, "New Post", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :body, placeholder: "What's on your mind?" ,class: "w-full border-2 rounded-md px-4 py-2 leading-5 transition duration-150 ease-in-out sm:text-sm
        sm:leading-5 focus:outline-none focus:border-blue-500 h-32"%>
    <br>
    <%= form.button "Post" , class: "items-center bg-blue-500 hover:bg-blue-600 focus:outline-none focus:shadow-outline-blue text-white py-2 px-4 rounded-md transition duration-300 gap-2 my-5" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="pb-7 mx-6" id="<%= dom_id post %>">
  <p><%= post.body %></p>
  <div class="flex flex-row mt-3 text-sky-100 text-bold">
    <div class="flex flex-col ml-auto mr-2">
      <%= link_to post.user.email, "#", class:"text-right text-slate-700"%>
      <%= link_to post.created_at.to_formatted_s(:db)  , post, class: "text-right text-xs text-gray-500"%>
    </div>
    <%= image_tag avatar_url(post.user), class: "rounded-full h-9 w-9 hover:object-scale-up ml-0" %>
  </div>
</div>

app/views/posts/show.html.erb
<p class="font-bold text-3xl mb-3 mx-6"><%= @post.topic.title%></p>
<%= render @post %>

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Topic title" %>
    <%= form.text_field :title %>
  </div>
  <h2>New Post</h2>
  <div>
    <%= form.fields_for :posts do |post_subform| %>
      <%= post_subform.label :body %>
      <%= post_subform.text_area :body %>
    <% end %>
  </div>
  <div>
    <%= form.submit "Create Topic with a Post"%>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render "form", topic: @topic %>

<br>

app/views/topics/show.html.erb
<p class="font-bold text-3xl mb-3 mx-6"><%= @topic.title%></p>

<div>
  <%= render @posts%>
</div>

<div class="text-center pb-8"><%== pagy_nav(@pagy, pagy_id: @topic.id)%></div>

<% if user_signed_in? %>
  <div class="text-center"><%= render partial: "posts/form", locals: {post: @topic.posts.new }%></div>
<% end %>